In [ ]:
#This Program will detect if the email is spam(1) or not(0)

**IMPORTING THE LIBRARIES**

In [1]:
#import Libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

**LOADING THE DATA**

In [29]:
#Load the data
from google.colab import files
upload = files.upload()

Saving email.csv to email.csv


In [30]:
#Read The File
df =pd.read_csv('email.csv',encoding='latin-1')

#Print the First five rows of data
df.head(5)

type                                               text Unnamed: 2  \
0     0  Go until jurong point, crazy.. Available only ...        NaN   
1     0                      Ok lar... Joking wif u oni...        NaN   
2     1  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3     0  U dun say so early hor... U c already then say...        NaN   
4     0  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [34]:
new_df=df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
new_df

type                                               text
0        0  Go until jurong point, crazy.. Available only ...
1        0                      Ok lar... Joking wif u oni...
2        1  Free entry in 2 a wkly comp to win FA Cup fina...
3        0  U dun say so early hor... U c already then say...
4        0  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567     1  This is the 2nd time we have tried 2 contact u...
5568     0              Will Ì_ b going to esplanade fr home?
5569     0  Pity, * was in mood for that. So...any other s...
5570     0  The guy did some bitching but I acted like i'd...
5571     0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [35]:
#Printing the shape[rows and columns]
new_df.shape

(5572, 2)

In [36]:
#get the columns name
new_df.columns

Index(['type', 'text'], dtype='object')

In [39]:
#checking for duplicates and removing them
new_df.drop_duplicates(inplace=True)
new_df.shape

(5169, 2)

In [40]:
#Show the number of missing data in each column
new_df.isnull().sum()

type    0
text    0
dtype: int64

In [41]:
#Dwonloading the stopwords packages using nltk(Natural Language Toolkit)
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [45]:
#Defining the function for processing the text
def process_text(text):

  1#remove punctuation
  2#remove stopwords
  3#return a set of clean text words

  #1
  nopunc=[char for char in text if char not in string.punctuation]
  nopunc=''.join(nopunc)

  #2
  clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

**Tokenizing means splitting your text into minimal meaningful units. It is a mandatory step before any kind of processing.**

In [46]:
#Show the tokenization(a list of words known as lemmas)
new_df['text'].head().apply(process_text)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: text, dtype: object

In [51]:
#converting the collection of texts to a token to use in the vector matrix
from sklearn.feature_extraction.text import CountVectorizer
#message_bow = bag of words
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

**TRAINING THE MODEL**

In [52]:
#spliting the data in 80% training and 20% testing using the train_test_split method
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow,df['type'], test_size=0.2, random_state=0)

In [53]:
#get the shape of messages.bow
messages_bow.shape

(5572, 11302)

In [63]:
#using the naives baiyes classifier from sklearn.naive_bayes import MultinomialNB
classifier= MultinomialNB().fit(X_train,y_train)

In [64]:
#printing the predictions
print(classifier.predict(X_train))

#printing the y_train values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


#from the above ouput the model training are pretty much matched up


TESTING THE TRAINED MODEL FOR PREDICTION

In [71]:
#Evaluating the model using the training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred =classifier.predict(X_test)
print(classification_report(y_test,pred))
print()
print('Confusion matrix \n',confusion_matrix(y_test,pred))
print()
print('Accuracy Score\n',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97       949
           1       0.81      0.93      0.87       166

    accuracy                           0.96      1115
   macro avg       0.90      0.95      0.92      1115
weighted avg       0.96      0.96      0.96      1115


Confusion matrix 
 [[914  35]
 [ 12 154]]

Accuracy Score
 0.957847533632287
